image: jangrewe/gitlab-ci-android

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/


stages:
- build
- test
- release
- deploy
build:
lintDebug:
  stage: build
  script:
  - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
assembleDebug:
  stage: build
  script:
  - ./gradlew assembleDebug

testDebug:
  stage: test
  script:
  - ./gradlew -Pci --console=plain :app:testDebug
push_latest:
  stage: push
  only:
    - master
  script:
    - docker tag dcr.faked.org/gitlab-ci/android:${CI_COMMIT_SHORT_SHA} dcr.faked.org/gitlab-ci/android:latest
    - docker push dcr.faked.org/gitlab-ci/android:latest

push_tag:
  stage: push
  only:
    - tags
  script:
    - docker tag dcr.faked.org/gitlab-ci/android:${CI_COMMIT_SHORT_SHA} dcr.faked.org/gitlab-ci/android:${CI_COMMIT_TAG}
    - docker push dcr.faked.org/gitlab-ci/android:${CI_COMMIT_TAG}
